### PR TITLE
Clickhouse jsonnet

### PR DESCRIPTION
**Pull request by mrinal1209**
Add support for Clickhouse Dashboard

@adivinho @puneet0191

### CODE REVIEW

**Review by adivinho — CHANGES_REQUESTED** [review]
It's missed setting value mappings to 0 in your case.

Screenshot_20190624_125352

**Comment by mrinal1209** [comment]
@adivinho please review the requested changes

**Comment by adivinho** [comment]
It's missed parameters Y-Min = 0 and Decimals = 0 in your template.
Screenshot_20190701_132015

Screenshot_20190701_132431


Also it's missed parameter Decimals = 2 here
Screenshot_20190701_132231

and Y-Min = 0 in charts "Memory Tracking" and "File Opens"

**Comment by mrinal1209** [comment]
@adivinho please review again

**Comment by adivinho** [comment]
The parameter Y-Min is still not assigned for the chart "Memory Tracking".

**Review by adivinho — APPROVED** [review]

**Review by puneet0191 — APPROVED** [review]

**Pull request merged**
