### PR TITLE
Numa overview jsonnet

### PR DESCRIPTION
**Pull request by mrinal1209**
Add support for NUMA_Overview Dashboard
@adivinho  @puneet0191

### CODE REVIEW

**Review by adivinho — CHANGES_REQUESTED** [review]
Some extra elements are present on the dashboard
Screenshot_20190618_184353
Here is the original dashboard
Screenshot_20190618_184408

**Comment by mrinal1209** [comment]
> Some extra elements are present on the dashboard
> Screenshot_20190618_184353
> Here is the original dashboard
> Screenshot_20190618_184408

I have pushed the changes, please review again @adivinho

**Comment by adivinho** [comment]
> I have pushed the changes, please review again @adivinho

The variable node has to be present for the dashboard.
Screenshot_20190618_191327

Here is the result from the template.
Screenshot_20190618_191018

**Comment by mrinal1209** [comment]
@adivinho please review the new changes

**Comment by adivinho** [comment]
Could you may sure that the correct file was pushed?
IMHO already fixed issues are back. Some extra elements are shown on the dashboard again.

Screenshot_20190716_222251

**Comment by mrinal1209** [comment]
@adivinho @puneet0191 please review again I am hidden the extra templates

**Comment by adivinho** [comment]
The variable Mountpoint has to be hidden too.
Also I have missed extra spaces issue in descriptions.
Screenshot_20190723_223341

**Comment by mrinal1209** [comment]
@adivinho please help to test I have made the suggested changes.

**Review by adivinho — CHANGES_REQUESTED** [review]
There are two extra Graph elements in the row "Total"
Screenshot_20190724_184932
Elements without parameter "Repeat" have to be removed.

Also there is one extra element in the row "Node 0"
Screenshot_20190724_185252

**Comment by adivinho** [comment]
The section "Free Memory Pages" -> Node 0 is perfect now.
But I still can see two extra singlestats in "Free Memory Pages" -> "Total"

Also could you fix a formula KernelStack in "Node 0 - NUMA Memory Usage Types". There is an extra symbol ")".

Screenshot_20190725_135643
Screenshot_20190725_135315

**Comment by adivinho** [comment]
The template can't be processed now.
Screenshot_20190729_125238

**Review by adivinho — APPROVED** [review]

**Pull request merged**
